version: '3.2'

services:
  test_db:
    container_name: mysql_test
    image: mysql:5.6
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: be_test
    expose:
      - "3306"
    ports:
      - "33062:3306"

  node_graph:
    build: .
    container_name: node
    environment:
      DB_HOST: test_db
      DB_NAME: be_test
      DB_PASSWORD: root
      DB_USER: root
    depends_on:
      - test_db
    volumes:
      - "${PWD}/client:/app/client:delegated"
      - "${PWD}/public:/app/public:delegated"
      - "${PWD}/server:/app/server:delegated"
      - "${PWD}/package.json:/app/package.json:delegated"
    entrypoint:
      - /app/entrypoint.sh
    ports:
      - "9001:9001"
      - "36625:36625" # hot loader websocket
