export const LOAD_DESIGNERS           = 'LOAD_DESIGNERS';
export const LOAD_DESIGNERS_FULFILLED = `${LOAD_DESIGNERS}_FULFILLED`;
export const LOAD_DESIGNERS_PENDING   = `${LOAD_DESIGNERS}_PENDING`;

export const LOAD_ROOMS               = 'LOAD_ROOMS';
export const LOAD_ROOMS_FULFILLED     = `${LOAD_ROOMS}_FULFILLED`;
export const LOAD_ROOMS_PENDING       = `${LOAD_ROOMS}_PENDING`;
